import os
from sys import platform

if platform == 'win32':
    os.system('echo ====================================')
    os.system('echo Updating Python Tools')
    os.system('echo ====================================')
    os.system('pip install --upgrade pip')
    os.system('pip install chardet==3.0.4 certifi==2017.7.27.1')
    os.system('pip install utils requests==2.18.3')
    os.system('echo ====================================')
    os.system('echo Creating Virtual Environment')
    os.system('echo ====================================')
    os.system('conda create -y -n venv-prtgen python=2.7.13')
    os.system('echo ====================================')
    os.system('echo Installing Requirements')
    os.system('echo ====================================')
    os.system('activate venv-prtgen & python -m pip install --upgrade pip & pip install -r ./requirements/requirements.txt')
    os.system('deactivate venv-prtgen')
    os.system('echo ====================================')
    os.system('echo Installation Complete')
    os.system('echo ====================================')
elif platform == 'darwin':
    os.system('echo ====================================')
    os.system('echo Updating Python Tools')
    os.system('echo ====================================')
    os.system('pip install --upgrade pip')
    os.system('pip install chardet==3.0.4 certifi==2017.7.27.1')
    os.system('pip install utils requests==2.18.3')
    os.system('echo ====================================')
    os.system('echo Updating Brew Tools')
    os.system('echo ====================================')
    os.system('xcode-select --install')
    os.system('/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)')
    os.system('brew update')
    os.system('brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer')
    os.system('brew upgrade pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer')
    os.system('echo ====================================')
    os.system('echo Creating Virtual Environment')
    os.system('echo ====================================')
    os.system('conda create -y -n venv-prtgen python=2.7.13')
    os.system('echo ====================================')
    os.system('echo Installing Requirements')
    os.system('echo ====================================')
    os.system('source activate venv-prtgen & python -m pip install --upgrade pip & python -m pip install --upgrade cython==0.27.3 pip install chardet==3.0.4 certifi==2017.7.27.1 & pip install -r ./requirements/requirements_darwin.txt')
    os.system('source deactivate venv-prtgen')
    os.system('echo ====================================')
    os.system('echo Installation Complete')
    os.system('echo ====================================')